ALTER TABLE member_review DROP CONSTRAINT member_review_pkey;

ALTER TABLE member_review
    ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;

CREATE INDEX idx_member_review_member_id ON member_review (member_id);
