CREATE TABLE notice (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id    BIGINT NOT NULL REFERENCES member (id),
    title       TEXT NOT NULL,
    content     TEXT NOT NULL,
    is_pinned   BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_notice_admin_id ON notice (admin_id);
CREATE INDEX idx_notice_created_at ON notice (created_at);
CREATE INDEX idx_notice_pinned_created_at ON notice (is_pinned, created_at);

CREATE TABLE notice_read (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notice_id   BIGINT NOT NULL REFERENCES notice (id) ON DELETE CASCADE,
    member_id   BIGINT NOT NULL REFERENCES member (id),
    read_at     TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_notice_read_notice_member UNIQUE (notice_id, member_id)
);

CREATE INDEX idx_notice_read_notice_id ON notice_read (notice_id);
CREATE INDEX idx_notice_read_member_id ON notice_read (member_id);
