CREATE TABLE assignment (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id                BIGINT NOT NULL REFERENCES member (id),
    title                   TEXT NOT NULL,
    content                 TEXT NOT NULL,
    due_at                  TIMESTAMPTZ NOT NULL,
    allow_late_submission   BOOLEAN NOT NULL DEFAULT FALSE,
    created_at              TIMESTAMPTZ NOT NULL,
    updated_at              TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_assignment_admin_id ON assignment (admin_id);
CREATE INDEX idx_assignment_due_at ON assignment (due_at);
CREATE INDEX idx_assignment_created_at ON assignment (created_at);
