CREATE TABLE attachment (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_name   TEXT NOT NULL,
    stored_name     TEXT NOT NULL,
    storage_key     TEXT NOT NULL,
    extension       TEXT NOT NULL,
    size_kb         BIGINT NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_attachment_storage_key UNIQUE (storage_key)
);

CREATE TABLE notice_attachment (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notice_id       BIGINT NOT NULL REFERENCES notice (id) ON DELETE CASCADE,
    attachment_id   BIGINT NOT NULL REFERENCES attachment (id) ON DELETE CASCADE,
    CONSTRAINT uk_notice_attachment_notice_attachment UNIQUE (notice_id, attachment_id)
);

CREATE INDEX idx_notice_attachment_notice_id ON notice_attachment (notice_id);
CREATE INDEX idx_notice_attachment_attachment_id ON notice_attachment (attachment_id);

CREATE TABLE assignment_attachment (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_id   BIGINT NOT NULL REFERENCES assignment (id) ON DELETE CASCADE,
    attachment_id   BIGINT NOT NULL REFERENCES attachment (id) ON DELETE CASCADE,
    CONSTRAINT uk_assignment_attachment_assignment_attachment UNIQUE (assignment_id, attachment_id)
);

CREATE INDEX idx_assignment_attachment_assignment_id ON assignment_attachment (assignment_id);
CREATE INDEX idx_assignment_attachment_attachment_id ON assignment_attachment (attachment_id);
