CREATE TABLE submission (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_id   BIGINT NOT NULL REFERENCES assignment (id) ON DELETE CASCADE,
    student_id      BIGINT NOT NULL REFERENCES member (id),
    text_content    TEXT,
    is_late         BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_submission_assignment_student UNIQUE (assignment_id, student_id)
);

CREATE INDEX idx_submission_assignment_id ON submission (assignment_id);
CREATE INDEX idx_submission_student_id ON submission (student_id);
CREATE INDEX idx_submission_created_at ON submission (created_at);

CREATE TABLE submission_attachment (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id   BIGINT NOT NULL REFERENCES submission (id) ON DELETE CASCADE,
    attachment_id   BIGINT NOT NULL REFERENCES attachment (id) ON DELETE CASCADE,
    CONSTRAINT uk_submission_attachment_submission_attachment UNIQUE (submission_id, attachment_id)
);

CREATE INDEX idx_submission_attachment_submission_id ON submission_attachment (submission_id);
CREATE INDEX idx_submission_attachment_attachment_id ON submission_attachment (attachment_id);
