CREATE TABLE submission_comment (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id   BIGINT NOT NULL REFERENCES submission (id) ON DELETE CASCADE,
    author_id       BIGINT NOT NULL REFERENCES member (id),
    content         TEXT NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_submission_comment_submission_id ON submission_comment (submission_id);
CREATE INDEX idx_submission_comment_submission_id_created_at_id ON submission_comment (submission_id, created_at, id);
CREATE INDEX idx_submission_comment_author_id ON submission_comment (author_id);
