CREATE TABLE notice_comment (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notice_id       BIGINT NOT NULL REFERENCES notice (id) ON DELETE CASCADE,
    author_id       BIGINT NOT NULL REFERENCES member (id),
    content         TEXT NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_notice_comment_notice_id ON notice_comment (notice_id);
CREATE INDEX idx_notice_comment_notice_id_created_at_id ON notice_comment (notice_id, created_at, id);
CREATE INDEX idx_notice_comment_author_id ON notice_comment (author_id);
